development: &default
  es_bin: '../bin/elasticsearch-8.12.1/bin/elasticsearch'
  host: 'http://localhost:9200'
  port: '9200'
test:
  es_bin: '../bin/elasticsearch-8.12.1/bin/elasticsearch'
  host: 'http://localhost:9250'
  port: '9250'